/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReparoRouteImport } from './routes/reparo'
import { Route as RedeRouteImport } from './routes/rede'
import { Route as IndexRouteImport } from './routes/index'

const ReparoRoute = ReparoRouteImport.update({
  id: '/reparo',
  path: '/reparo',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeRoute = RedeRouteImport.update({
  id: '/rede',
  path: '/rede',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rede': typeof RedeRoute
  '/reparo': typeof ReparoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rede': typeof RedeRoute
  '/reparo': typeof ReparoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rede': typeof RedeRoute
  '/reparo': typeof ReparoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rede' | '/reparo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rede' | '/reparo'
  id: '__root__' | '/' | '/rede' | '/reparo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RedeRoute: typeof RedeRoute
  ReparoRoute: typeof ReparoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reparo': {
      id: '/reparo'
      path: '/reparo'
      fullPath: '/reparo'
      preLoaderRoute: typeof ReparoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rede': {
      id: '/rede'
      path: '/rede'
      fullPath: '/rede'
      preLoaderRoute: typeof RedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RedeRoute: RedeRoute,
  ReparoRoute: ReparoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
