/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DiscoRouteImport } from './routes/disco'
import { Route as LimpezaRouteImport } from './routes/limpeza'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as RedesRouteImport } from './routes/redes'
import { Route as ReparoRouteImport } from './routes/reparo'
import { Route as SistemaRouteImport } from './routes/sistema'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoRoute = DiscoRouteImport.update({
  id: '/disco',
  path: '/disco',
  getParentRoute: () => rootRouteImport,
} as any)
const LimpezaRoute = LimpezaRouteImport.update({
  id: '/limpeza',
  path: '/limpeza',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesRoute = RedesRouteImport.update({
  id: '/redes',
  path: '/redes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReparoRoute = ReparoRouteImport.update({
  id: '/reparo',
  path: '/reparo',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaRoute = SistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/disco': typeof DiscoRoute
  '/limpeza': typeof LimpezaRoute
  '/logs': typeof LogsRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/redes': typeof RedesRoute
  '/reparo': typeof ReparoRoute
  '/sistema': typeof SistemaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/disco': typeof DiscoRoute
  '/limpeza': typeof LimpezaRoute
  '/logs': typeof LogsRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/redes': typeof RedesRoute
  '/reparo': typeof ReparoRoute
  '/sistema': typeof SistemaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/disco': typeof DiscoRoute
  '/limpeza': typeof LimpezaRoute
  '/logs': typeof LogsRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/redes': typeof RedesRoute
  '/reparo': typeof ReparoRoute
  '/sistema': typeof SistemaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/disco'
    | '/limpeza'
    | '/logs'
    | '/monitoramento'
    | '/redes'
    | '/reparo'
    | '/sistema'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/disco'
    | '/limpeza'
    | '/logs'
    | '/monitoramento'
    | '/redes'
    | '/reparo'
    | '/sistema'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/disco'
    | '/limpeza'
    | '/logs'
    | '/monitoramento'
    | '/redes'
    | '/reparo'
    | '/sistema'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DiscoRoute: typeof DiscoRoute
  LimpezaRoute: typeof LimpezaRoute
  LogsRoute: typeof LogsRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
  RedesRoute: typeof RedesRoute
  ReparoRoute: typeof ReparoRoute
  SistemaRoute: typeof SistemaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disco': {
      id: '/disco'
      path: '/disco'
      fullPath: '/disco'
      preLoaderRoute: typeof DiscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limpeza': {
      id: '/limpeza'
      path: '/limpeza'
      fullPath: '/limpeza'
      preLoaderRoute: typeof LimpezaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redes': {
      id: '/redes'
      path: '/redes'
      fullPath: '/redes'
      preLoaderRoute: typeof RedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparo': {
      id: '/reparo'
      path: '/reparo'
      fullPath: '/reparo'
      preLoaderRoute: typeof ReparoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema': {
      id: '/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DiscoRoute: DiscoRoute,
  LimpezaRoute: LimpezaRoute,
  LogsRoute: LogsRoute,
  MonitoramentoRoute: MonitoramentoRoute,
  RedesRoute: RedesRoute,
  ReparoRoute: ReparoRoute,
  SistemaRoute: SistemaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
