/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SistemaRouteImport } from './routes/sistema'
import { Route as ReparoRouteImport } from './routes/reparo'
import { Route as RedeRouteImport } from './routes/rede'
import { Route as LimpezaRouteImport } from './routes/limpeza'
import { Route as DiscoRouteImport } from './routes/disco'
import { Route as IndexRouteImport } from './routes/index'

const SistemaRoute = SistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const ReparoRoute = ReparoRouteImport.update({
  id: '/reparo',
  path: '/reparo',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeRoute = RedeRouteImport.update({
  id: '/rede',
  path: '/rede',
  getParentRoute: () => rootRouteImport,
} as any)
const LimpezaRoute = LimpezaRouteImport.update({
  id: '/limpeza',
  path: '/limpeza',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoRoute = DiscoRouteImport.update({
  id: '/disco',
  path: '/disco',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disco': typeof DiscoRoute
  '/limpeza': typeof LimpezaRoute
  '/rede': typeof RedeRoute
  '/reparo': typeof ReparoRoute
  '/sistema': typeof SistemaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disco': typeof DiscoRoute
  '/limpeza': typeof LimpezaRoute
  '/rede': typeof RedeRoute
  '/reparo': typeof ReparoRoute
  '/sistema': typeof SistemaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disco': typeof DiscoRoute
  '/limpeza': typeof LimpezaRoute
  '/rede': typeof RedeRoute
  '/reparo': typeof ReparoRoute
  '/sistema': typeof SistemaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/disco' | '/limpeza' | '/rede' | '/reparo' | '/sistema'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/disco' | '/limpeza' | '/rede' | '/reparo' | '/sistema'
  id:
    | '__root__'
    | '/'
    | '/disco'
    | '/limpeza'
    | '/rede'
    | '/reparo'
    | '/sistema'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoRoute: typeof DiscoRoute
  LimpezaRoute: typeof LimpezaRoute
  RedeRoute: typeof RedeRoute
  ReparoRoute: typeof ReparoRoute
  SistemaRoute: typeof SistemaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sistema': {
      id: '/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparo': {
      id: '/reparo'
      path: '/reparo'
      fullPath: '/reparo'
      preLoaderRoute: typeof ReparoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rede': {
      id: '/rede'
      path: '/rede'
      fullPath: '/rede'
      preLoaderRoute: typeof RedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limpeza': {
      id: '/limpeza'
      path: '/limpeza'
      fullPath: '/limpeza'
      preLoaderRoute: typeof LimpezaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disco': {
      id: '/disco'
      path: '/disco'
      fullPath: '/disco'
      preLoaderRoute: typeof DiscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoRoute: DiscoRoute,
  LimpezaRoute: LimpezaRoute,
  RedeRoute: RedeRoute,
  ReparoRoute: ReparoRoute,
  SistemaRoute: SistemaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
